#!/bin/bash

#$ -q all.q
#$ -V
#$ -cwd
#$ -pe smp 16

module load mafft/7.487
module load IQ-TREE/1.7-beta18
module load RevTrans/1.4

mafft --maxiterate 1000 --thread $NSLOTS --auto 3C-like_proteinase.aa.nr100.fasta > 3C-like_proteinase.aa.nr100.aln

revtrans.py 3C-like_proteinase.nt.nr100.fasta 3C-like_proteinase.aa.nr100.aln -match name 3C-like_proteinase.nt.nr100.aln

iqtree -s 3C-like_proteinase.nt.nr100.aln -st CODON1 -B 1000 -T $NSLOTS -m GY+F
