#!/bin/bash

#$ -q all.q
#$ -V
#$ -cwd
#$ -tc 48
#$ -t 1-8
#$ -hold_jid 21370

module load Python/3.7.2
input_path=`ls -1d /Storage/data1/bia.estevam/PegarBordas_files/sequencesFilesRATT/North_America/*_Divisor* /Storage/data1/bia.estevam/PegarBordas_files/sequencesFilesRATT/Europe/*_Divisor*|head -n $SGE_TASK_ID|tail -n1`
region=`basename $input_path`
mkdir $region

#cp ${input_path}/*.embl ${region}
cd $region
#sed -i 's/.final ; ; ; ; ;/.final ; ; ;/' *.embl
python3 ../extracting_proteins_pathlib_3Clike.py . . 3C-like_proteinase
